### ISSUE TITLE
To combine between two or more queries

### ISSUE THREAD

**Issue by AvivSan90** [orbardugo/Hahot-Hameshulash#13]
**User Story:**
As the client of the app i would like to make couple of queries at the same time, to example: I would like to get all the males that lives in jerusalem, at ages 18-20.

**Test senarios:**
1. click on gender and add male/female.
2. click on age and choose range ages.
3. click on city and choose specific city.

**Expected results:**
1. See results on query result labels

**Comment by LevyIdan** [comment]
we created the option to combine a several queries
