### ISSUE TITLE
Create graph by C#

### ISSUE THREAD

**Issue by AvivSan90** [orbardugo/Hahot-Hameshulash#14]
**User Story:**
As the client of the app i would like to make a query, and see as a graph not only as list.
for example - see precentage of "בית חרדי" at jerusalem by female, from all females from Jerusalem.

**Test senarios:**
1.create the query and click on graph.

**Expected results:**
1. A "Cake Graph" or "Bar Graph" will appear on screen.

**Comment by orbardugo** [comment]
we create 2 kinds of graphs, Pie and Column
