### ISSUE TITLE
Meeting with the costumers

### ISSUE THREAD

**Issue by orbardugo** [orbardugo/Hahot-Hameshulash#22]
- [x] present the application and get feedbacks

- [x] get queries that they want to present on graph

the meeting will be at 7.6.17,09:00

**Comment by orbardugo** [comment]
Update, the meeting will be at 7.6.17,09:00

**Comment by sabagsapir** [comment]
Done. new issues were created as results of the meeting

**Comment by orbardugo** [comment]
Meeting summary:

we met with the customers and we presented them the app, they were very Satisfied!
they told us that the app is very simple to use even for people that no have any technical knowlage.
on the meeting they ask for few more things:
* Adding count of rows in result table
* Adding option to print ther reports
* Adding total amount of arrivals query
* Changing "city" query to "area" query
* Adding percentage or\and count option to charts results

we asked for them to give us a new excel file with some fixes we need.
We got a final meeting set up with the costumers on the 20.6.17 12:00 at their place.
