### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [orbardugo/Hahot-Hameshulash#4]
- דף צוות חסר שונות הצוות
- ניהול סיכונים כללי ולא ספציפי לפרויקט
- לוח זמנים חסר
- תיאור תכנון שלבי הפרויקט חסר

**Comment by orbardugo** [comment]
@kob-e  
המשימות הושלמו, לבדיקתך החוזרת
תודה.
