### ISSUE TITLE
Create ZFR Wiki page

### ISSUE THREAD

**Issue by orbardugo** [orbardugo/Hahot-Hameshulash#7]
## Checklist:

- [x] Version Control
- [x] Create prototype #6  
- [x] [User Manual](https://github.com/orbardugo/Hahot-Hameshulash/wiki/user-manual)
- [x] [Readme - for new development](https://github.com/orbardugo/Hahot-Hameshulash/blob/master/README.md#development)
- [x] [Create new labels](https://github.com/orbardugo/Hahot-Hameshulash/labels)
- [x] Create schedule tasks - new project
- [x]  Next Iteration's planning

**Comment by robi-y** [comment]
you need to remove all redundant text from new issues

**Comment by orbardugo** [comment]
Done!

**Comment by robi-y** [comment]
It's about time...
