### ISSUE TITLE
Mission 5 - ZFR: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [orbardugo/Hahot-Hameshulash#9]
- אין איטרציה הבאה
- איפה קישור לאב טיפוס

**Comment by AvivSan90** [comment]
@kob-e כידוע איננו מפתחים אפליקצית רשת, לכן אין לנו קישור לאב טיפוס, העלנו צילומי מסך של האפליקציה.

**Comment by sabagsapir** [comment]
Done.
